AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MLOps - Trigger SageMaker Pipeline via Lambda

Resources:
  TriggerPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trigger-pipeline-fn
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: lambda/trigger_pipeline/
      Timeout: 120
      MemorySize: 512
      Role: arn:aws:iam::975049948583:role/LambdaSageMakerInferencePolicy
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /trigger
            Method: post
      Environment:
        Variables:
          SAGEMAKER_ROLE_ARN: arn:aws:iam::975049948583:role/LambdaSageMakerInferencePolicy
          PROCESSING_IMAGE_URI: 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3
          SCRIPT_S3_URI: s3://swo-ngoctran-public/jobs/preprocessing_kmeans.py
          OUTPUT_S3_PATH: s3://swo-ngoctran-public/inference_result/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sagemaker:CreateProcessingJob
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::swo-ngoctran-public/*
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: arn:aws:s3:::swo-ngoctran-public/*

Outputs:
  ApiTriggerEndpoint:
    Description: "API Gateway endpoint for triggering preprocessing pipeline"
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/trigger
