name: Trigger Preprocessing KMeans

on:
  push:
    paths:
      - 'pipelines/01_preprocessing_kmeans/input_files.json'

jobs:
  trigger-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read input file list from JSON
        id: load_input
        run: |
          FILE_LIST=$(jq -c '.input_files' pipelines/01_preprocessing_kmeans/input_files.json)
          echo "file_list=$FILE_LIST" >> $GITHUB_OUTPUT

      - name: Debug - Show file list
        run: echo "Input files = ${{ steps.load_input.outputs.file_list }}"

      - name: Trigger API Gateway (Lambda)
        run: |
          echo "Triggering Lambda via API Gateway..."
          PAYLOAD=$(jq -nc --argjson files '${{ steps.load_input.outputs.file_list }}' \
            '{pipeline: "preprocessing_kmeans", params: {input_files: $files}}')
          echo "Payload = $PAYLOAD"
          curl -X POST "${{ secrets.TRIGGER_API_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
