name: Trigger Preprocessing KMeans

on:
  push:
    paths:
      - 'pipelines/01_preprocessing_kmeans/input_files.json'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read input file list
        id: load_input
        run: |
          FILE_LIST=$(jq -c '.input_files' pipelines/01_preprocessing_kmeans/input_files.json)
          echo "file_list=$FILE_LIST" >> $GITHUB_OUTPUT

      - name: Trigger API Gateway
        run: |
          curl -X POST "${{ secrets.TRIGGER_API_ENDPOINT }}" \
            -H "Content-Type: application/json" \
            -d "{\"pipeline\":\"preprocessing_kmeans\",\"params\":{\"input_files\":${{ steps.load_input.outputs.file_list }}}}"
