name: Upload All Python Files + Build SAM

on:
  push:
    paths:
      - '**/*.py'
      - 'config/global_config.json'
      - 'template.yaml'

jobs:
  upload-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read S3 base path from config
        id: config
        run: |
          BASE_PATH=$(jq -r '.s3_script_path' pipelines/01_preprocessing_kmeans/config.json)
          echo "s3_base=$BASE_PATH" >> $GITHUB_OUTPUT

      - name: Detect changed Python files
        id: changed
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main | grep '\.py$' || true)
          echo "$CHANGED_FILES" > changed_files.txt
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug - Show changed Python files
        run: |
          echo "Changed Python files:"
          cat changed_files.txt

      - name: Upload changed .py files to matching S3 folders
        run: |
          BASE_S3=${{ steps.config.outputs.s3_base }}

          while read -r file; do
            if [ -n "$file" ]; then
              CLEANED_FILE=$(echo "$file" | sed 's|^\./||')
              S3_TARGET="$BASE_S3/$CLEANED_FILE"

              echo "Uploading $CLEANED_FILE → $S3_TARGET"
              aws s3 cp "$CLEANED_FILE" "$S3_TARGET"
            fi
          done < changed_files.txt

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: false

      - name: SAM Build
        run: sam build

      - name: SAM Deploy (auto-confirm)
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name mlops-trigger-stack
