name: Upload Preprocessing Script + Build SAM

on:
  push:
    paths:
      - 'pipelines/01_preprocessing_kmeans/preprocessing_kmeans.py'
      - 'config/global_config.json'
      - 'pipelines/01_preprocessing_kmeans/config.json'
      - 'template.yaml'

jobs:
  upload-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Read S3 destination from config
        id: config
        run: |
          DEST=$(jq -r '.s3_script_path' pipelines/01_preprocessing_kmeans/config.json)
          echo "s3_uri=$DEST" >> $GITHUB_OUTPUT

      - name: Upload preprocessing_kmeans.py to S3
        run: |
          aws s3 cp pipelines/01_preprocessing_kmeans/preprocessing_kmeans.py \
            "${{ steps.config.outputs.s3_uri }}"

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: latest

      - name: SAM Build
        run: sam build

      - name: SAM Deploy (auto-confirm)
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name mlops-trigger-stack
